-- Buraq Markets + Supabase schema
-- Run this once in Supabase Dashboard > SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  country text,
  account_type text,
  preferred_platform text,
  client_id text unique,
  kyc_status text not null default 'Pending',
  created_at timestamptz not null default now()
);

create table if not exists public.trading_accounts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  account_number text unique not null,
  account_name text not null default 'Buraq Standard',
  balance numeric(18,2) not null default 0,
  equity numeric(18,2) not null default 0,
  free_margin numeric(18,2) not null default 0,
  today_pl numeric(18,2) not null default 0,
  leverage text not null default '1:500',
  platform text not null default 'MT5',
  margin_level numeric(12,2) not null default 0,
  status text not null default 'ACTIVE',
  created_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  trading_account_id bigint references public.trading_accounts(id) on delete set null,
  transaction_date timestamptz not null default now(),
  type text not null,
  reference text unique not null,
  amount numeric(18,2) not null,
  status text not null default 'Pending'
);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  full_name text not null,
  email text not null,
  subject text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.trading_accounts enable row level security;
alter table public.transactions enable row level security;
alter table public.contact_messages enable row level security;

-- Profiles: users can read/update only their own profile.
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles for select using (auth.uid() = id);
drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles for insert with check (auth.uid() = id);
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

-- Trading accounts and transactions are private to the logged-in user.
drop policy if exists "accounts_select_own" on public.trading_accounts;
create policy "accounts_select_own" on public.trading_accounts for select using (auth.uid() = user_id);
drop policy if exists "transactions_select_own" on public.transactions;
create policy "transactions_select_own" on public.transactions for select using (auth.uid() = user_id);

-- Any visitor may submit a contact message; users may also see only their own messages.
drop policy if exists "contact_insert_anyone" on public.contact_messages;
create policy "contact_insert_anyone" on public.contact_messages for insert with check (true);
drop policy if exists "contact_select_own" on public.contact_messages;
create policy "contact_select_own" on public.contact_messages for select using (auth.uid() = user_id);

-- Automatically create a profile when an Auth user is created.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, phone, country, account_type, preferred_platform, client_id)
  values (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'phone',
    new.raw_user_meta_data->>'country',
    new.raw_user_meta_data->>'account_type',
    new.raw_user_meta_data->>'preferred_platform',
    'BM-' || upper(substr(replace(new.id::text, '-', ''), 1, 8))
  )
  on conflict (id) do nothing;

  insert into public.trading_accounts (user_id, account_number, account_name, platform)
  values (new.id, 'BM-' || floor(100000 + random() * 899999)::text, coalesce(new.raw_user_meta_data->>'account_type', 'Standard'), coalesce(new.raw_user_meta_data->>'preferred_platform', 'MT5'))
  on conflict (account_number) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
