-- Buraq Markets: Client Verification (KYC) — run once in Supabase SQL Editor
-- Run this AFTER supabase-schema.sql and supabase-deposit-policy.sql

-- 1) Table to store submitted KYC documents
create table if not exists public.kyc_documents (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  id_type text not null,
  id_number text not null,
  id_document_path text not null,
  selfie_path text not null,
  status text not null default 'Pending',
  admin_note text,
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz
);

alter table public.kyc_documents enable row level security;

-- Users can submit their own KYC documents
drop policy if exists "kyc_insert_own" on public.kyc_documents;
create policy "kyc_insert_own"
on public.kyc_documents for insert
with check (auth.uid() = user_id);

-- Users can view their own submitted documents/status
drop policy if exists "kyc_select_own" on public.kyc_documents;
create policy "kyc_select_own"
on public.kyc_documents for select
using (auth.uid() = user_id);

-- NOTE: There is no public "update" policy on purpose.
-- You (the admin) approve/reject documents from the Supabase Table Editor
-- (or SQL Editor) using your own account, which is not subject to these
-- browser-facing RLS policies in the same way — the public/browser key
-- can never approve or reject a submission.

-- 2) Private storage bucket for ID documents and selfies
insert into storage.buckets (id, name, public)
values ('kyc-documents', 'kyc-documents', false)
on conflict (id) do nothing;

-- Users may upload only into their own folder: kyc-documents/{their-user-id}/...
drop policy if exists "kyc_storage_insert_own" on storage.objects;
create policy "kyc_storage_insert_own"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'kyc-documents'
  and (storage.foldername(name))[1] = auth.uid()::text
);

-- Users may view only their own uploaded files
drop policy if exists "kyc_storage_select_own" on storage.objects;
create policy "kyc_storage_select_own"
on storage.objects for select to authenticated
using (
  bucket_id = 'kyc-documents'
  and (storage.foldername(name))[1] = auth.uid()::text
);
